#version 450
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct Input
{
    uint x;
    uint y;
};

struct Output
{
    uint sum;
};

layout(std140, set = 0, binding = 0x00) uniform Camera
{
    mat4 view;
    mat4 proj;
} camera;

layout(std430, set = 0, binding = 0x01) readonly buffer InputBuffer
{
    Input inputs[];
};

layout(std430, set = 0, binding = 0x02) buffer OutputBuffer
{
    Output outputs[];
};

void main()
{
    const uint index = gl_GlobalInvocationID.x;

    if (index > inputs.length()) return;

    const Input i = inputs[index];
    outputs[index].sum = i.x + i.y;
}
