#version 450
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct InstanceData {
    mat4 transform;
    uint textureId;
    uint pad[3];
};

layout(std430, set = 0, binding = 0x01) readonly buffer Transforms {
    mat4 transforms[];
};

layout(std430, set = 0, binding = 0x02) buffer Instances {
    InstanceData instances[];
} buf;

layout(push_constant) uniform Params {
    uint count;
    float scale;
} pc;

void main()
{
    uint i = gl_GlobalInvocationID.x;
}
