#pragma once

#include <vulkan/vulkan.h>

namespace ascen
{
    enum DescriptorType
    {
        UBO           = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
        UBO_DYNAMIC   = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC,
        SSBO          = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
        SSBO_DYNAMIC  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC,
        IMAGE         = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
        SAMPLER       = VK_DESCRIPTOR_TYPE_SAMPLER,
        IMAGE_SAMPLER = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
    };

    enum DescriptorStage
    {
        VERTEX  = VK_SHADER_STAGE_VERTEX_BIT,
        PIXEL   = VK_SHADER_STAGE_FRAGMENT_BIT,
        COMPUTE = VK_SHADER_STAGE_COMPUTE_BIT,
    };

    typedef enum BufferUsageFlagBits
    {
        BUFFER_USAGE_VERTEX       = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
        BUFFER_USAGE_INDEX        = VK_BUFFER_USAGE_INDEX_BUFFER_BIT,
        BUFFER_USAGE_UNIFORM      = VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT,
        BUFFER_USAGE_STORAGE      = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
        BUFFER_USAGE_INDIRECT     = VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT,
        BUFFER_USAGE_TRANSFER_SRC = VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
        BUFFER_USAGE_TRANSFER_DST = VK_BUFFER_USAGE_TRANSFER_DST_BIT,
    } BufferUsageFlagBits;

    //typedef uint32_t BufferUsageFlags;
    using BufferUsageFlags = uint32_t;

    typedef enum BufferMemoryFlagBits
    {
        BUFFER_MEMORY_HOST = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
        BUFFER_MEMORY_LOCAL = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,
    } BufferMemoryFlagBits;

    //typedef uint32_t BufferMemoryFlags;
    using BufferMemoryFlags = uint32_t;

    enum class TextureType
    {
        NONE,
        IMAGE,
        DEPTH,
    };

    enum AttachmentType
    {
        ATTACHMENT_PRESENT,
        ATTACHMENT_COLOR,
        ATTACHMENT_DEPTH
    };

    enum Format
    {
        FORMAT_RGBA8_SRGB = VK_FORMAT_R8G8B8A8_SRGB,
    };

    enum StoreOp
    {
        STORE_OP_STORE = VK_ATTACHMENT_STORE_OP_STORE,
        STORE_OP_NA    = VK_ATTACHMENT_STORE_OP_DONT_CARE,
        STORE_OP_NONE  = VK_ATTACHMENT_STORE_OP_NONE,
    };

    enum LoadOp
    {
        LOAD_OP_LOAD  = VK_ATTACHMENT_LOAD_OP_LOAD,
        LOAD_OP_CLEAR = VK_ATTACHMENT_LOAD_OP_CLEAR,
        LOAD_OP_NA    = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
    };

    enum BindPoint
    {
        BIND_POINT_GRAPHICS = VK_PIPELINE_BIND_POINT_GRAPHICS,
        BIND_POINT_COMPUTE  = VK_PIPELINE_BIND_POINT_COMPUTE,
    };

    enum PipelineStage
    {
        PIPELINE_STAGE_DRAW_INDIRECT                  = VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT,
        PIPELINE_STAGE_VERTEX_INPUT                   = VK_PIPELINE_STAGE_VERTEX_INPUT_BIT,
        PIPELINE_STAGE_VERTEX_SHADER                  = VK_PIPELINE_STAGE_VERTEX_SHADER_BIT,
        PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER    = VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT,
        PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER = VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT,
        PIPELINE_STAGE_GEOMETRY_SHADER                = VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT,
        PIPELINE_STAGE_FRAGMENT_SHADER                = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
        PIPELINE_STAGE_EARLY_FRAGMENT_TESTS           = VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,
        PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT        = VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT,
        PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT        = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
        PIPELINE_STAGE_COMPUTE_SHADER                 = VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        PIPELINE_STAGE_TRANSFER                       = VK_PIPELINE_STAGE_TRANSFER_BIT,
    };

    using  PipelineStageFlag = uint32_t;

    enum AccessMask
    {
        ACCESS_INDIRECT_COMMAND_READ          = VK_ACCESS_INDIRECT_COMMAND_READ_BIT,
        ACCESS_INDEX_READ                     = VK_ACCESS_INDEX_READ_BIT,
        ACCESS_VERTEX_ATTRIBUTE_READ          = VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT,
        ACCESS_UNIFORM_READ                   = VK_ACCESS_UNIFORM_READ_BIT,
        ACCESS_INPUT_ATTACHMENT_READ          = VK_ACCESS_INPUT_ATTACHMENT_READ_BIT,
        ACCESS_SHADER_READ                    = VK_ACCESS_SHADER_READ_BIT,
        ACCESS_SHADER_WRITE                   = VK_ACCESS_SHADER_WRITE_BIT,
        ACCESS_COLOR_ATTACHMENT_READ          = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT,
        ACCESS_COLOR_ATTACHMENT_WRITE         = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
        ACCESS_DEPTH_STENCIL_ATTACHMENT_READ  = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT,
        ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
        ACCESS_TRANSFER_READ                  = VK_ACCESS_TRANSFER_READ_BIT,
        ACCESS_TRANSFER_WRITE                 = VK_ACCESS_TRANSFER_WRITE_BIT,
        ACCESS_HOST_READ                      = VK_ACCESS_HOST_READ_BIT,
        ACCESS_HOST_WRITE                     = VK_ACCESS_HOST_WRITE_BIT,
        ACCESS_MEMORY_READ                    = VK_ACCESS_MEMORY_READ_BIT,
        ACCESS_MEMORY_WRITE                   = VK_ACCESS_MEMORY_WRITE_BIT,
        ACCESS_NONE                           = VK_ACCESS_NONE,
    };

    using AccessMaskFlag = uint32_t;

}
