#version 450
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct Entity
{
    vec3 position;
    uint _pad0;
    vec3 rotation;
    uint _pad1;
    vec3 scale;

    uint isVisible;
    uint meshCount;
    uint meshOffset;
    uint _pad2[2];
};


layout(std140, set = 0, binding = 0x00) uniform Camera
{
    mat4 view;
    mat4 proj;
} camera;

layout(std430, set = 0, binding = 0x01) buffer Entities
{
    Entity entities[];
};

void main()
{
    uint entityIdx = gl_GlobalInvocationID.x;
    if (entityIdx >= entities.length())
    {
        return;
    }

    Entity entity = entities[entityIdx];

    vec4 pos = (camera.proj * camera.view) * vec4(entity.position, 1.0);

    bool inside =
        (pos.x >= -pos.w && pos.x <= pos.w) &&
        (pos.y >= -pos.w && pos.y <= pos.w) &&
        (pos.z >= -pos.w && pos.z <= pos.w);

    entities[entityIdx].isVisible = inside ? 1 : 0;
}